include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    # Relax some strict stylistic rules to match project formatting preferences
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    unawaited_futures: false

analyzer:
  exclude:
    - "lib/***.g.dart"
    - "**/*.g.dart"
