name: wassistant
description: "A Flutter project that provides tools for WhatsApp, such as generating QR codes, chat links, and vCards."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2
  image_gallery_saver: ^2.0.3
  country_code_picker: ^3.0.0
  google_mobile_ads: ^5.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
