// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRQ8gJaOvc_8OQn26e5Fej-mjyWKZ3GhE',
    appId: '1:977829078223:web:c30b978be3f7061ab8c3ba',
    messagingSenderId: '977829078223',
    projectId: 'wassistant-707',
    authDomain: 'wassistant-707.firebaseapp.com',
    storageBucket: 'wassistant-707.firebasestorage.app',
    measurementId: 'G-77KQ0TLVME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9YcbCx6fVdkIZxXhLp_FZJvqDvPZf5wI',
    appId: '1:977829078223:android:8b4c5e0f2d3a1b9c8c3ba',
    messagingSenderId: '977829078223',
    projectId: 'wassistant-707',
    storageBucket: 'wassistant-707.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmKvPJXvJ0P_qI5xU9NhZ8fLkY6nMZqRg',
    appId: '1:977829078223:ios:7f2e1c8d9b0a3f6e8c3ba',
    messagingSenderId: '977829078223',
    projectId: 'wassistant-707',
    storageBucket: 'wassistant-707.firebasestorage.app',
    iosBundleId: 'com.example.wassistant',
  );
}
