#!/usr/bin/env python3
"""
API Documentation Generator for WAssistant
INTJ: Systematic documentation, maintainable codebase
"""
import os
import subprocess
from pathlib import Path
import json


class DocumentationGenerator:
    """Generate comprehensive API documentation"""

    def __init__(self, project_root: Path):
        self.project_root = project_root
        self.docs_dir = project_root / "docs" / "api"
        self.docs_dir.mkdir(parents=True, exist_ok=True)

    def generate_dart_docs(self) -> bool:
        """Generate Dart API documentation using dartdoc"""
        print("📚 Generating Dart API documentation...")

        try:
            # Run dartdoc
            result = subprocess.run(
                ["dart", "doc", "."],
                cwd=self.project_root,
                capture_output=True,
                text=True,
                timeout=300,
            )

            if result.returncode == 0:
                print("✅ Dart documentation generated successfully")
                print(f"   Output: {self.project_root / 'doc' / 'api'}")
                return True
            else:
                print(f"❌ Dart documentation failed: {result.stderr}")
                return False

        except Exception as e:
            print(f"❌ Error generating Dart docs: {e}")
            return False

    def generate_python_docs(self) -> bool:
        """Generate Python documentation using pdoc"""
        print("📚 Generating Python API documentation...")

        python_dirs = ["python_scripts", "tools"]

        try:
            for python_dir in python_dirs:
                dir_path = self.project_root / python_dir
                if not dir_path.exists():
                    continue

                # Install pdoc if not present
                subprocess.run(
                    ["pip", "install", "pdoc3"],
                    capture_output=True,
                )

                # Generate docs
                output_dir = self.docs_dir / python_dir
                result = subprocess.run(
                    [
                        "pdoc",
                        "--html",
                        "--output-dir",
                        str(output_dir),
                        str(dir_path),
                    ],
                    capture_output=True,
                    text=True,
                    timeout=120,
                )

                if result.returncode == 0:
                    print(f"✅ Python docs generated: {python_dir}")
                else:
                    print(f"⚠️  Python docs warning for {python_dir}: {result.stderr}")

            return True

        except Exception as e:
            print(f"❌ Error generating Python docs: {e}")
            return False

    def generate_openapi_spec(self) -> bool:
        """Generate OpenAPI specification for REST APIs (future)"""
        print("📚 Generating OpenAPI specification...")

        # Placeholder for future REST API documentation
        openapi_spec = {
            "openapi": "3.0.0",
            "info": {
                "title": "WAssistant API",
                "description": "WhatsApp Tools & Utilities API",
                "version": "1.4.1",
                "contact": {
                    "name": "WAssistant Support",
                    "url": "https://wassistant-707.web.app",
                },
            },
            "servers": [
                {
                    "url": "https://wassistant-707.web.app",
                    "description": "Production server",
                }
            ],
            "paths": {},
            "components": {
                "schemas": {},
            },
        }

        spec_file = self.docs_dir / "openapi.json"
        with open(spec_file, "w") as f:
            json.dump(openapi_spec, f, indent=2)

        print(f"✅ OpenAPI spec generated: {spec_file}")
        return True

    def generate_markdown_index(self) -> bool:
        """Generate markdown index for all documentation"""
        print("📚 Generating documentation index...")

        index_content = """# WAssistant API Documentation

## Overview

This directory contains comprehensive API documentation for the WAssistant project.

## Documentation Types

### 1. Dart/Flutter API Documentation
- **Location**: `doc/api/index.html`
- **Generated by**: dartdoc
- **Covers**: All Dart classes, methods, properties
- **Usage**: Open `index.html` in browser

### 2. Python API Documentation
- **Location**: `docs/api/python_scripts/` and `docs/api/tools/`
- **Generated by**: pdoc
- **Covers**: Python automation scripts and tools
- **Usage**: Open `index.html` in each directory

### 3. OpenAPI Specification
- **Location**: `docs/api/openapi.json`
- **Format**: OpenAPI 3.0
- **Covers**: REST API endpoints (future)
- **Usage**: Import into Swagger UI or Postman

### 4. Architecture Documentation
- **Location**: `docs/architecture/`
- **Format**: Markdown (ADRs)
- **Covers**: Architectural decisions and patterns
- **Usage**: Read with any markdown viewer

## Generating Documentation

### Dart Documentation
```bash
dart doc .
```

### Python Documentation
```bash
python tools/generate_docs.py --python
```

### All Documentation
```bash
python tools/generate_docs.py --all
```

## INTJ Principles

Documentation follows systematic, logical principles:
- **Completeness**: Every public API documented
- **Consistency**: Standard format across all docs
- **Maintainability**: Auto-generated from code comments
- **Accessibility**: Multiple formats for different needs

## Contributing

When adding new features:
1. Add comprehensive code comments
2. Follow Dart documentation conventions (`///` for public APIs)
3. Regenerate docs before committing
4. Update this index if adding new doc types

## Links

- [Main README](../../README.md)
- [Architecture Decisions](../architecture/README.md)
- [Contributing Guide](../../CONTRIBUTING.md)
"""

        index_file = self.docs_dir / "README.md"
        index_file.write_text(index_content)

        print(f"✅ Documentation index generated: {index_file}")
        return True

    def generate_all(self):
        """Generate all documentation"""
        print("\n" + "=" * 70)
        print("GENERATING API DOCUMENTATION")
        print("=" * 70 + "\n")

        results = {
            "dart": self.generate_dart_docs(),
            "python": self.generate_python_docs(),
            "openapi": self.generate_openapi_spec(),
            "index": self.generate_markdown_index(),
        }

        print("\n" + "=" * 70)
        print("DOCUMENTATION GENERATION SUMMARY")
        print("=" * 70)

        for doc_type, success in results.items():
            status = "✅" if success else "❌"
            print(f"{status} {doc_type.capitalize()}")

        print("=" * 70 + "\n")

        return all(results.values())


def main():
    """Generate API documentation"""
    import argparse

    parser = argparse.ArgumentParser(description="Generate API documentation")
    parser.add_argument("--dart", action="store_true", help="Generate Dart docs only")
    parser.add_argument("--python", action="store_true", help="Generate Python docs only")
    parser.add_argument("--openapi", action="store_true", help="Generate OpenAPI spec only")
    parser.add_argument("--all", action="store_true", help="Generate all documentation")
    args = parser.parse_args()

    project_root = Path(__file__).parent.parent
    generator = DocumentationGenerator(project_root)

    if args.all or not any([args.dart, args.python, args.openapi]):
        generator.generate_all()
    else:
        if args.dart:
            generator.generate_dart_docs()
        if args.python:
            generator.generate_python_docs()
        if args.openapi:
            generator.generate_openapi_spec()
        generator.generate_markdown_index()


if __name__ == "__main__":
    main()
